### ISSUE TITLE
Consider replacing unescape with decodeURIComponent

### ISSUE THREAD

**Issue by Pengxn** [xn-02f/md5#10]
`unescape()` is not strictly deprecated in Annex B of the **ECMA-262** standard.

More information on [MDN docs unescape() function
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape)

https://github.com/xn-02f/md5/blob/41c08272cf4e0aa3a87665e647bb9e4dea4e6d2c/md5.js#L14

> **Quote**: The `unescape()` function computes a new string in which hexadecimal escape sequences are replaced with the character that it represents. The escape sequences might be introduced by a function like escape. Usually, `decodeURI` or `decodeURIComponent` are preferred over `unescape`.

**Comment by huiyifyj** [comment]
`unescape` was deprecated, but browser compatibility is still high.
This issue still needs to be considered.

**Comment by Pengxn** [comment]
As far as I am concerned, recommend to use `decodeURI` or `decodeURIComponent`.

**Comment by huiyifyj** [comment]
An error occurred if you use `decodeURI` during the testing process.
More informations about differences between `decodeURI` and `decodeURIComponent`, to visit to [ECMAScript® Language Specification #15.1.3 URI Handling Function Properties](https://ecma-international.org/ecma-262/5.1/#sec-15.1.3).
> Especially uriReserved ::: one of   (`;` `/` `?` `:` `@` `&` `=` `+` `$` `,`)

SO, i will new a branch to replacing `unescape` with `decodeURIComponent`.

**Comment by huiyifyj** [comment]
Don't consider replacing `unescape()` with `decodeURIComponent()`.
More reasome to https://github.com/xn-02f/md5/pull/14#pullrequestreview-378895705

**Comment by Pengxn** [comment]
Close the issue.
